export const ADD_CARD = 'ADD_CARD';
export const FETCH_CITY_WEATHER = 'FETCH_CITY_WEATHER';
export const ADD_CITY_TO_LIST = 'ADD_CITY_TO_LIST';
export const SAVE_CITY_INFO = 'SAVE_CITY_INFO';
export const REMOVE_CITY_FROM_LIST = 'REMOVE_CITY_FROM_LIST';
export const ADD_CITY_TO_LIST_FAILURE = 'ADD_CITY_TO_LIST_FAILURE';
export const UPDATE_CITY_INFO = 'UPDATE_CITY_INFO';
